theme: jekyll-theme-minimal\ntitle: Алексей Кличников - Портфолио\ndescription: Senior Backend Developer | Microsoft Dynamics AX/365 Specialist\nshow_downloads: false\ngithub:\n  is_project_page: false\n  is_user_page: true
