theme: jekyll-theme-minimal
title: Александр - Портфолио
description: Senior Backend Developer | Microsoft Dynamics AX2012 Senior Developer
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
