theme: jekyll-theme-minimal
title: Алексей Кличников - Портфолио
description: Senior Backend Developer | Microsoft Dynamics AX/365 Specialist
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
